//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIApplication) DeepCopyInto(out *APIApplication) {
	*out = *in
	if in.AcceptMappedClaims != nil {
		in, out := &in.AcceptMappedClaims, &out.AcceptMappedClaims
		*out = new(bool)
		**out = **in
	}
	if in.KnownClientApplications != nil {
		in, out := &in.KnownClientApplications, &out.KnownClientApplications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OAuth2PermissionScopes != nil {
		in, out := &in.OAuth2PermissionScopes, &out.OAuth2PermissionScopes
		*out = make([]PermissionScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreAuthorizedApplications != nil {
		in, out := &in.PreAuthorizedApplications, &out.PreAuthorizedApplications
		*out = make([]PreAuthorizedApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppRoleAllowedMemberTypes != nil {
		in, out := &in.AppRoleAllowedMemberTypes, &out.AppRoleAllowedMemberTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequestedAccessTokenVersion != nil {
		in, out := &in.RequestedAccessTokenVersion, &out.RequestedAccessTokenVersion
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIApplication.
func (in *APIApplication) DeepCopy() *APIApplication {
	if in == nil {
		return nil
	}
	out := new(APIApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRegCredConfig) DeepCopyInto(out *AppRegCredConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRegCredConfig.
func (in *AppRegCredConfig) DeepCopy() *AppRegCredConfig {
	if in == nil {
		return nil
	}
	out := new(AppRegCredConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraAppRegistration) DeepCopyInto(out *EntraAppRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraAppRegistration.
func (in *EntraAppRegistration) DeepCopy() *EntraAppRegistration {
	if in == nil {
		return nil
	}
	out := new(EntraAppRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntraAppRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraAppRegistrationList) DeepCopyInto(out *EntraAppRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EntraAppRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraAppRegistrationList.
func (in *EntraAppRegistrationList) DeepCopy() *EntraAppRegistrationList {
	if in == nil {
		return nil
	}
	out := new(EntraAppRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntraAppRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraAppRegistrationSpec) DeepCopyInto(out *EntraAppRegistrationSpec) {
	*out = *in
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(AppRegCredConfig)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InformationUrl != nil {
		in, out := &in.InformationUrl, &out.InformationUrl
		*out = new(InformationUrl)
		**out = **in
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.IdentifierUris != nil {
		in, out := &in.IdentifierUris, &out.IdentifierUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OptionalClaims != nil {
		in, out := &in.OptionalClaims, &out.OptionalClaims
		*out = new(OptionalClaims)
		(*in).DeepCopyInto(*out)
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(APIApplication)
		(*in).DeepCopyInto(*out)
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(WebApplication)
		(*in).DeepCopyInto(*out)
	}
	if in.SPA != nil {
		in, out := &in.SPA, &out.SPA
		*out = new(SPAApplication)
		(*in).DeepCopyInto(*out)
	}
	if in.PublicClient != nil {
		in, out := &in.PublicClient, &out.PublicClient
		*out = new(PublicClientApplication)
		(*in).DeepCopyInto(*out)
	}
	if in.ServicePrincipal != nil {
		in, out := &in.ServicePrincipal, &out.ServicePrincipal
		*out = new(ServicePrincipalParams)
		**out = **in
	}
	if in.RequiredResourceAccess != nil {
		in, out := &in.RequiredResourceAccess, &out.RequiredResourceAccess
		*out = make([]RequiredResourceAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraAppRegistrationSpec.
func (in *EntraAppRegistrationSpec) DeepCopy() *EntraAppRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(EntraAppRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraAppRegistrationStatus) DeepCopyInto(out *EntraAppRegistrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastRun.DeepCopyInto(&out.LastRun)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraAppRegistrationStatus.
func (in *EntraAppRegistrationStatus) DeepCopy() *EntraAppRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(EntraAppRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraSecurityGroup) DeepCopyInto(out *EntraSecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraSecurityGroup.
func (in *EntraSecurityGroup) DeepCopy() *EntraSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(EntraSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntraSecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraSecurityGroupList) DeepCopyInto(out *EntraSecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EntraSecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraSecurityGroupList.
func (in *EntraSecurityGroupList) DeepCopy() *EntraSecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(EntraSecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntraSecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraSecurityGroupSpec) DeepCopyInto(out *EntraSecurityGroupSpec) {
	*out = *in
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(ProviderSpec)
		**out = **in
	}
	if in.GroupTypes != nil {
		in, out := &in.GroupTypes, &out.GroupTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = new([]Owners)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Owners, len(*in))
			copy(*out, *in)
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new([]Members)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Members, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraSecurityGroupSpec.
func (in *EntraSecurityGroupSpec) DeepCopy() *EntraSecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(EntraSecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraSecurityGroupStatus) DeepCopyInto(out *EntraSecurityGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedMemberUsers != nil {
		in, out := &in.ManagedMemberUsers, &out.ManagedMemberUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedMemberGroups != nil {
		in, out := &in.ManagedMemberGroups, &out.ManagedMemberGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedMemberServicePrincipals != nil {
		in, out := &in.ManagedMemberServicePrincipals, &out.ManagedMemberServicePrincipals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OwnerGroups != nil {
		in, out := &in.OwnerGroups, &out.OwnerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OwnerServicePrincipals != nil {
		in, out := &in.OwnerServicePrincipals, &out.OwnerServicePrincipals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraSecurityGroupStatus.
func (in *EntraSecurityGroupStatus) DeepCopy() *EntraSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(EntraSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplicitGrantSettings) DeepCopyInto(out *ImplicitGrantSettings) {
	*out = *in
	if in.EnableAccessTokenIssuance != nil {
		in, out := &in.EnableAccessTokenIssuance, &out.EnableAccessTokenIssuance
		*out = new(bool)
		**out = **in
	}
	if in.EnableIDTokenIssuance != nil {
		in, out := &in.EnableIDTokenIssuance, &out.EnableIDTokenIssuance
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplicitGrantSettings.
func (in *ImplicitGrantSettings) DeepCopy() *ImplicitGrantSettings {
	if in == nil {
		return nil
	}
	out := new(ImplicitGrantSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InformationUrl) DeepCopyInto(out *InformationUrl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InformationUrl.
func (in *InformationUrl) DeepCopy() *InformationUrl {
	if in == nil {
		return nil
	}
	out := new(InformationUrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Members) DeepCopyInto(out *Members) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Members.
func (in *Members) DeepCopy() *Members {
	if in == nil {
		return nil
	}
	out := new(Members)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionalClaim) DeepCopyInto(out *OptionalClaim) {
	*out = *in
	if in.AdditionalProperties != nil {
		in, out := &in.AdditionalProperties, &out.AdditionalProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Essential != nil {
		in, out := &in.Essential, &out.Essential
		*out = new(bool)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionalClaim.
func (in *OptionalClaim) DeepCopy() *OptionalClaim {
	if in == nil {
		return nil
	}
	out := new(OptionalClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionalClaims) DeepCopyInto(out *OptionalClaims) {
	*out = *in
	if in.AccessToken != nil {
		in, out := &in.AccessToken, &out.AccessToken
		*out = make([]OptionalClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IDToken != nil {
		in, out := &in.IDToken, &out.IDToken
		*out = make([]OptionalClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SAML2Token != nil {
		in, out := &in.SAML2Token, &out.SAML2Token
		*out = make([]OptionalClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionalClaims.
func (in *OptionalClaims) DeepCopy() *OptionalClaims {
	if in == nil {
		return nil
	}
	out := new(OptionalClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Owners) DeepCopyInto(out *Owners) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Owners.
func (in *Owners) DeepCopy() *Owners {
	if in == nil {
		return nil
	}
	out := new(Owners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionScope) DeepCopyInto(out *PermissionScope) {
	*out = *in
	if in.AdminConsentDescription != nil {
		in, out := &in.AdminConsentDescription, &out.AdminConsentDescription
		*out = new(string)
		**out = **in
	}
	if in.AdminConsentDisplayName != nil {
		in, out := &in.AdminConsentDisplayName, &out.AdminConsentDisplayName
		*out = new(string)
		**out = **in
	}
	if in.UserConsentDescription != nil {
		in, out := &in.UserConsentDescription, &out.UserConsentDescription
		*out = new(string)
		**out = **in
	}
	if in.UserConsentDisplayName != nil {
		in, out := &in.UserConsentDisplayName, &out.UserConsentDisplayName
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionScope.
func (in *PermissionScope) DeepCopy() *PermissionScope {
	if in == nil {
		return nil
	}
	out := new(PermissionScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreAuthorizedApplication) DeepCopyInto(out *PreAuthorizedApplication) {
	*out = *in
	if in.PermissionIds != nil {
		in, out := &in.PermissionIds, &out.PermissionIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreAuthorizedApplication.
func (in *PreAuthorizedApplication) DeepCopy() *PreAuthorizedApplication {
	if in == nil {
		return nil
	}
	out := new(PreAuthorizedApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicClientApplication) DeepCopyInto(out *PublicClientApplication) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicClientApplication.
func (in *PublicClientApplication) DeepCopy() *PublicClientApplication {
	if in == nil {
		return nil
	}
	out := new(PublicClientApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredResourceAccess) DeepCopyInto(out *RequiredResourceAccess) {
	*out = *in
	if in.ResourceAccess != nil {
		in, out := &in.ResourceAccess, &out.ResourceAccess
		*out = make([]ResourceAccess, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredResourceAccess.
func (in *RequiredResourceAccess) DeepCopy() *RequiredResourceAccess {
	if in == nil {
		return nil
	}
	out := new(RequiredResourceAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAccess) DeepCopyInto(out *ResourceAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAccess.
func (in *ResourceAccess) DeepCopy() *ResourceAccess {
	if in == nil {
		return nil
	}
	out := new(ResourceAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SPAApplication) DeepCopyInto(out *SPAApplication) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SPAApplication.
func (in *SPAApplication) DeepCopy() *SPAApplication {
	if in == nil {
		return nil
	}
	out := new(SPAApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePrincipalParams) DeepCopyInto(out *ServicePrincipalParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePrincipalParams.
func (in *ServicePrincipalParams) DeepCopy() *ServicePrincipalParams {
	if in == nil {
		return nil
	}
	out := new(ServicePrincipalParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebApplication) DeepCopyInto(out *WebApplication) {
	*out = *in
	if in.HomePageURL != nil {
		in, out := &in.HomePageURL, &out.HomePageURL
		*out = new(string)
		**out = **in
	}
	if in.ImplicitGrantSettings != nil {
		in, out := &in.ImplicitGrantSettings, &out.ImplicitGrantSettings
		*out = new(ImplicitGrantSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebApplication.
func (in *WebApplication) DeepCopy() *WebApplication {
	if in == nil {
		return nil
	}
	out := new(WebApplication)
	in.DeepCopyInto(out)
	return out
}
